---

- import_tasks: ssl.yml
  when: GEN_CERTS|default(false)|bool

- import_tasks: generic.yml

- name: push certificates to kubernetes masters
  when: (master_node|default(false)|bool and initial_setup|default(false)|bool)
  synchronize:
    src: /tmp/etcpkifiles/
    dest: /etc/kubernetes/pki

- import_tasks: kubeadm.yml
  when: master_node|default(false)|bool

- name: copy kubelet config
  copy:
    src: kubelet.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  tags:
    - kubelet

- name: restart kubelet
  systemd:
    name: kubelet.service
    enabled: true
    state: restarted
    daemon_reload: yes
  tags:
    - kubelet
